### ISSUE TITLE
cannot import name 'ExtensionError'

### ISSUE THREAD

**Issue by dputhier** [sphinx-contrib/googleanalytics#2]
Hi,
When using sphinxcontrib.googleanalytics with Python 3.6.7, I'm getting the following error:

    Extension error:
    Could not import extension sphinxcontrib.googleanalytics (exception: cannot import name 'ExtensionError')

I managed to get it work using this workaround:

     # https://jiangsheng.net/2019/01/05/fix-sphinxcontrib-googleanalytics-on-sphinx-1-8/
     # Fix is to change googleanalytics.py Line 4 
     # from
     # from sphinx.application import ExtensionError
     # to
     # from sphinx.errors import ExtensionError

However, this would be better to provide a fix as the module is not usable in this version in a production environment.
Best

**Comment by SuperKogito** [comment]
Since this is still not fixed, despite the existing pull request. I am leaving this here for Linux based system users & Sphinx (2.1.0) with python3. As @dputhier already mentioned, the fix is to replace `from sphinx.application import ExtensionError` with  `from sphinx.errors import ExtensionError` in `/usr/local/lib/python3.6/dist-packages/sphinxcontrib_googleanalytics.../sphinxcontrib/googleanalytics.py`

**Comment by dputhier** [comment]
Just for information,  the file of interest can also be located in  
.../lib/python3.7/site-packages/sphinxcontrib/googleanalytics.py

**Comment by pyhys** [comment]
As a workaround you can add this to the top of your conf.py file:
```
# Workaround for issue https://github.com/sphinx-contrib/googleanalytics/issues/2
# Note that a warning still will be issued "unsupported object from its setup() function"
# Remove this workaround when the issue has been resolved upstream
import sphinx.application
import sphinx.errors
sphinx.application.ExtensionError = sphinx.errors.ExtensionError
```

**Comment by jelmer** [comment]
I believe this is obsolete now #1 has been merged.
